<?php
//Autoload Composer
require __DIR__.'/vendor/autoload.php';

//Use JWT
use Firebase\JWT\JWT;

//Start a session if it is not initialized yet
if (session_status() == PHP_SESSION_NONE)
{
	session_start();
}

//Ideally, the key needs to be changed on a regular basis.
define("JWT_KEY", "eb91ef73a14b43a01b798c9f3a8771bf2b09b599caeb941ee1ddfe85470aedee"); // Generated by using bin2hex(random_bytes(32))

//The function for generating jwt tokens (generated by ChatGPT)
function generateJWTToken($isLoggedIn, $loggedInId)
{
	//Get the key for encoding and decoding jwt tokens
	$key = JWT_KEY;
	
	// Create token payload
	$payload = [
		'isLoggedIn' => $isLoggedIn,
        "id" => $loggedInId,
		"iat" => time(), // Issued at
		"exp" => time() + (60 * 60) // Expire time in seconds (1 hour)
	];

	// Generate token
	$jwt = JWT::encode($payload, $key, 'HS256'); //Revising ChatGPT's code
    $_SESSION['jwt'] = $jwt;
}?>
